### ISSUE TITLE
-enable-libndi_newtek

### ISSUE THREAD

**Issue by under-score** [johanels/macos-FFmpegNDI#1]
Step 5 (configure) fails on my machine (os 10.12.6)  with unknown option "--enable-libndi_newtek".

**Comment by johanels** [comment]
Hi,

NDI support in FFmpeg was removed in the FFMPEG source on the 20th of March 2019.

https://github.com/FFmpeg/FFmpeg/commit/4b32f8b3ebfa011fcc5991bcaa97c3f5b61b49ad

This is from a license dispute with Newtek ( https://trac.ffmpeg.org/ticket/7589 ) and NDI support has now been removed from FFmpeg.

I will take these projects offline.

Apologies for the inconvenience.

Regards,

**Comment by johanels** [comment]
Hi,

From a user suggestion to rebase to the correct FFMPEG version:

git checkout n4.1.2

Regards,

JE
